EHT-643 Add namada testnet
encapsulate-xyz/namada-ansible pull request #1
Opened 2024-12-30 08:57 UTC by kowshikvajrala

2024-12-31 12:58 UTC, aditya-manit requested changes

2024-12-31 12:58 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +wal_file = "data/cs.wal/wal"
we should update this too

2024-12-31 12:58 UTC, aditya-manit commented on roles/node/defaults/main.yml
> +node_priv_validator_key_path: "{{ node_cometbft_dir }}/config/{{ node_priv_validator_key_file_name }}"
lets create another variable  node_cometbft_config_dir for {{ node_cometbft_dir }}/config/

2024-12-31 12:58 UTC, aditya-manit commented on roles/node/tasks/main.yml
> +    extracted_path:
1. is there a better way to do it ? maybe loop over the list in one go ? or create a map with the default names and the name we want ?
2. atleast one of these must be explicitly renamed to service identifier, or it wont work if its anything else than default node type

2024-12-31 12:58 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +chain_id = "housefire-alpaca.cc0d3e0c033be"
please fetch this from group vars

2024-12-31 12:58 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +indexer = "null"
can we create space otpimization setting variable like we create in cosmos and use it here

2024-12-31 12:58 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +laddr = "tcp://127.0.0.1:{{ namada[type].ports.rpc_port }}"
127.0.0.1 should be based on validator or fullnode, just like we did in cosmos

2024-12-31 12:58 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +wal_file = "data/cs.wal/wal"
is this data under cometbft ? if yes we can create a cometbft data dir

2025-01-02 08:29 UTC, kowshikvajrala commented on roles/node/templates/testnet/config.toml.j2
> +wal_file = "data/cs.wal/wal"
the directories under cometbft or being handled by the binary

2025-01-02 08:29 UTC, kowshikvajrala commented on roles/node/templates/testnet/config.toml.j2
> +wal_file = "data/cs.wal/wal"
do we need to create manually ?

2025-01-02 10:40 UTC, kowshikvajrala commented on roles/node/templates/testnet/config.toml.j2
> +tendermint_mode = "Full"
Can you please share the config

2025-01-02 19:03 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +priv_validator_state_file = "data/priv_validator_state.json"
maybe we should update these locations with our file path variables

2025-01-02 19:04 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +tendermint_mode = "Full"
This is what I have currently on mainnet validator: https://www.notion.so/encapsulate/Namada-16614f565a5080f1afebccc86247bc07?pvs=4#16f14f565a508045b1e8d6bb6d76a840

2025-01-03 05:24 UTC, aditya-manit commented on tasks/get_and_save_vault_secret.yml
> +      {% for key, value in vault_response.secret.items() -%}
didnt we remove this because it was causing the no line break

2025-01-03 05:54 UTC, aditya-manit commented on ansible.cfg
> +# vault_password_file = ansible_vault_password
please use ";" for comments in cfg from now on, I will explain in the call why

2025-01-04 08:29 UTC, aditya-manit requested changes

2025-01-04 08:29 UTC, aditya-manit commented on roles/node/vars/main.yml
> +node_service_default_binary_name:
create the mapping here, maybe somehting like

```ansible
node_binaries:
  namada_default:
    default_binary_name: "namada"
    dest_binary_name: "{{ service_identifier }}"
  namada_node:
    default_binary_name: "namadan"
    dest_binary_name: "namadan"
  namada_client:
    default_binary_name: "namadac"
    dest_binary_name: "namadac"
  namada_worker:
    default_binary_name: "namadaw"
    dest_binary_name: "namadaw"
```

2025-01-04 08:29 UTC, aditya-manit commented on roles/node/tasks/main.yml
> +    path_mapping:
here loop over node_binaries, avoid using indices please

2025-01-04 08:29 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +persistent_peers = "tcp://0ed550f6f3acc48505fb194ad7966d923db5f7bb@167.99.185.160:26656,tcp://3e254524b630ee5a1d0df6aa40b4ed1370b5e51a@74.50.93.254:26656"
please store persistent_peers and seeds as we did in cosmos repo

2025-01-04 08:29 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +pex = true
please check cosmos repo for all config settings, similarly we should create variables here as well

2025-01-04 08:29 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +priv_validator_key_file = "{{ node_cometbft_config_dir }}/priv_validator_key.json"
we should already have variables for priv_validator_key_file path and priv_validator_state_file path, if yes lets use them

2025-01-04 08:29 UTC, aditya-manit commented on roles/node/templates/testnet/config.toml.j2
> +external_address = ""
lets add this too, please check the cometbft seeting in cosmos ansible config file, and replicate all the variable here as well

2025-01-04 08:29 UTC, aditya-manit commented on roles/node/tasks/main.yml
> +    path_mapping:
use dict2items if needed

2025-01-10 04:26 UTC, aditya-manit approved these changes

2025-01-10 04:26 UTC, merged